### PR TITLE
Improve Example Solutions for Part 2

### PR DESCRIPTION
**Pull request by matt-humphrey**
The example solution for the second part removes 10 candies, and then adds 5 back, when the instructions are to simply remove 5.

I've updated the example solution so it just removes 5 candies, which I think is clearer, and makes more sense.

### CODE REVIEW

**Comment by BrooklinJazz** [comment]
Hi Matt! Thank you for making a PR.

This solution doesn't work. This example serves to highlight how keyword lists work.

We can't simply remove 5 candies, we can only remove elements in a list by an exact match.

for example, you can try the following in the IEx shell. Notice the result is still `[candies: 10]` instead of `[candies: 5]`.

```elixir
iex> [candies: 10] -- [candies: 5]
[candies: 10]
```

**Comment by matt-humphrey** [comment]
My bad! Apologies for wasting your time - I should have verified that before submitting the pull request.
At least it was a learning opportunity for me! Thanks for your patience and assistance.
I'll be more careful in future!

**Comment by BrooklinJazz** [comment]
Never apologies for taking the time to help the project 🙏 A huge thank you for reviewing the content and making a PR!

**Comment by BrooklinJazz** [comment]
Reach out if I can ever help with the curriculum or future PRs :)

**Pull request closed without merging**
